version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 8th-mile-website
    ports:
      - "3003:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - APP_EMAIL_1=${APP_EMAIL_1}
      - APP_PASSWORD_1=${APP_PASSWORD_1}
      - NEXT_PUBLIC_CASHFREE_MODE=${NEXT_PUBLIC_CASHFREE_MODE}
      - NEXT_PUBLIC_CASHFREE_CLIENT_ID=${NEXT_PUBLIC_CASHFREE_CLIENT_ID}
      - CASHFREE_CLIENT_SECRET=${CASHFREE_CLIENT_SECRET}
    restart: unless-stopped
